import * as readline from "node:readline/promises";
import { stdin, stdout } from "node:process";
import chalk from "chalk";
import type { PRInfo, ReviewResult } from "./types.js";

const severityColor = {
  critical: chalk.red.bold,
  warning: chalk.yellow,
  info: chalk.dim,
} as const;

const overallColor = {
  high: chalk.bgRed.white.bold,
  medium: chalk.bgYellow.black,
  low: chalk.bgGreen.black,
} as const;

export async function presentReview(
  pr: PRInfo,
  review: ReviewResult
): Promise<"comment" | "skip" | "quit"> {
  console.log();
  console.log(chalk.cyan("━".repeat(70)));
  console.log(
    chalk.bold(`  PR #${pr.number}: ${pr.title}`)
  );
  console.log(
    chalk.dim(
      `  by @${pr.author} · ${pr.owner}/${pr.repo} · ${pr.url}`
    )
  );
  console.log(chalk.cyan("━".repeat(70)));
  console.log();
  console.log(chalk.white(review.summary));
  console.log();

  if (review.concerns.length > 0) {
    console.log(
      chalk.bold(`  ${review.concerns.length} concern(s):`)
    );
    console.log();
    for (const [i, concern] of review.concerns.entries()) {
      const badge = severityColor[concern.severity](
        ` ${concern.severity.toUpperCase()} `
      );
      const location = concern.line
        ? `${concern.file}:${concern.line}`
        : concern.file;
      console.log(`  ${i + 1}. ${badge} ${chalk.bold(location)}`);
      console.log(`     ${concern.message}`);
      console.log();
    }
  } else {
    console.log(chalk.green("  ✓ No concerns found."));
    console.log();
  }

  console.log(
    `  Overall: ${overallColor[review.overallSeverity](` ${review.overallSeverity.toUpperCase()} `)}`
  );
  console.log();

  const rl = readline.createInterface({ input: stdin, output: stdout });
  try {
    const answer = await rl.question(
      chalk.bold("  [c]omment · [s]kip · [q]uit → ")
    );
    const choice = answer.trim().toLowerCase();
    if (choice === "c" || choice === "comment") return "comment";
    if (choice === "q" || choice === "quit") return "quit";
    return "skip";
  } finally {
    rl.close();
  }
}

export function formatReviewAsComment(review: ReviewResult): string {
  const lines: string[] = [
    "## 🤖 Automated Code Review",
    "",
    review.summary,
    "",
  ];

  if (review.concerns.length > 0) {
    lines.push("### Concerns");
    lines.push("");
    for (const concern of review.concerns) {
      const icon =
        concern.severity === "critical"
          ? "🔴"
          : concern.severity === "warning"
            ? "🟡"
            : "🔵";
      const location = concern.line
        ? `\`${concern.file}:${concern.line}\``
        : `\`${concern.file}\``;
      lines.push(`- ${icon} **${concern.severity}** ${location}: ${concern.message}`);
    }
    lines.push("");
  }

  lines.push(
    `**Overall severity: ${review.overallSeverity}**`
  );
  lines.push("");
  lines.push("---");
  lines.push("*Generated by ami-personal-automation*");

  return lines.join("\n");
}
